micronaut:
  application:
    name: openIdConnectOciDemo
  security:
    authentication: idtoken
    oauth2:
      clients:
        oci:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
          openid:
            issuer: ${OAUTH_ISSUER}
    endpoints:
      logout:
        enabled: true
        get-allowed: true